### ISSUE TITLE
Please consider add more scientific computing packages to the whitelist.

### ISSUE THREAD

**Issue by zhhzhc** [sonm-io/allowed-list#40]
The folloing scientific computing docker images do not harm supporters' machines, please consider put them into the whitelist.

1. Finite element mesh generator: gmsh, https://github.com/Tanatloc/Gmsh-docker

2. CFD software: openfoam, https://hub.docker.com/u/openfoam

3. Finite element package deal.II: https://hub.docker.com/r/dealii/dealii

4. scientific computing software Octave: https://hub.docker.com/r/compdatasci/octave-desktop

5. Finite element package FEnics: https://hub.docker.com/r/fenicsproject/stable

6. Scientific computing package: Julia, https://hub.docker.com/_/julia

7. SageMath is a free open-source mathematics software system licensed under the GPL: https://hub.docker.com/r/sagemath/sagemath/

8. FFmpeg is a command-line tool that converts audio or video formats. It can also capture and encode in real-time from various hardware and software sources such as a TV capture card. The project publishes a new release every three months on average. While release versions are available from the website for download, FFmpeg developers recommend that users compile the software from source using the latest build from their source code Git version control system.

ref: https://hub.docker.com/r/jrottenberg/ffmpeg/

9. Erlang is a programming language used to build massively scalable systems with high availability, ref: https://hub.docker.com/_/erlang

Please consider add all the essential toolkits for scientific computing into the whitelist, iexec's dapp board shows some of them, check: https://dapps.iex.ec/.

Thank you very much!

**Comment by emanaev** [comment]
The problem with these packages is that they process user's data, so customer can download some illegal data on supplier's PC. That can be revealed by authorities.
If the supplier can take this risk, he can just switch off whitelist check for anonymous customers.
Still we recommend SONM customers passing KYC procedure.
